package com.example.mapleapi.domain;

import com.example.mapleapi.domain.ItemEquipment.*;
import lombok.Getter;
import lombok.Setter;

import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.List;

/**
 * {
 *   "date": "2023-12-21T00:00+09:00",
 *   "character_gender": "string",
 *   "character_class": "string",
 *   "preset_no": 0,
 *   "item_equipment": [
 *     {
 *       "item_equipment_part": "string",
 *       "item_equipment_slot": "string",
 *       "item_name": "string",
 *       "item_icon": "string",
 *       "item_description": "string",
 *       "item_shape_name": "string",
 *       "item_shape_icon": "string",
 *       "item_gender": "string",
 *       "item_total_option": {
 *         "str": "string",
 *         "dex": "string",
 *         "int": "string",
 *         "luk": "string",
 *         "max_hp": "string",
 *         "max_mp": "string",
 *         "attack_power": "string",
 *         "magic_power": "string",
 *         "armor": "string",
 *         "speed": "string",
 *         "jump": "string",
 *         "boss_damage": "string",
 *         "ignore_monster_armor": "string",
 *         "all_stat": "string",
 *         "damage": "string",
 *         "equipment_level_decrease": 0,
 *         "max_hp_rate": "string",
 *         "max_mp_rate": "string"
 *       },
 *       "item_base_option": {
 *         "str": "string",
 *         "dex": "string",
 *         "int": "string",
 *         "luk": "string",
 *         "max_hp": "string",
 *         "max_mp": "string",
 *         "attack_power": "string",
 *         "magic_power": "string",
 *         "armor": "string",
 *         "speed": "string",
 *         "jump": "string",
 *         "boss_damage": "string",
 *         "ignore_monster_armor": "string",
 *         "all_stat": "string",
 *         "max_hp_rate": "string",
 *         "max_mp_rate": "string",
 *         "base_equipment_level": 0
 *       },
 *       "potential_option_grade": "string",
 *       "additional_potential_option_grade": "string",
 *       "potential_option_1": "string",
 *       "potential_option_2": "string",
 *       "potential_option_3": "string",
 *       "additional_potential_option_1": "string",
 *       "additional_potential_option_2": "string",
 *       "additional_potential_option_3": "string",
 *       "equipment_level_increase": 0,
 *       "item_exceptional_option": {
 *         "str": "string",
 *         "dex": "string",
 *         "int": "string",
 *         "luk": "string",
 *         "max_hp": "string",
 *         "max_mp": "string",
 *         "attack_power": "string",
 *         "magic_power": "string"
 *       },
 *       "item_add_option": {
 *         "str": "string",
 *         "dex": "string",
 *         "int": "string",
 *         "luk": "string",
 *         "max_hp": "string",
 *         "max_mp": "string",
 *         "attack_power": "string",
 *         "magic_power": "string",
 *         "armor": "string",
 *         "speed": "string",
 *         "jump": "string",
 *         "boss_damage": "string",
 *         "damage": "string",
 *         "all_stat": "string",
 *         "equipment_level_decrease": 0
 *       },
 *       "growth_exp": 0,
 *       "growth_level": 0,
 *       "scroll_upgrade": "string",
 *       "cuttable_count": "string",
 *       "golden_hammer_flag": "string",
 *       "scroll_resilience_count": "string",
 *       "scroll_upgradable_count": "string",
 *       "soul_name": "string",
 *       "soul_option": "string",
 *       "item_etc_option": {
 *         "str": "string",
 *         "dex": "string",
 *         "int": "string",
 *         "luk": "string",
 *         "max_hp": "string",
 *         "max_mp": "string",
 *         "attack_power": "string",
 *         "magic_power": "string",
 *         "armor": "string",
 *         "speed": "string",
 *         "jump": "string"
 *       },
 *       "starforce": "string",
 *       "starforce_scroll_flag": "string",
 *       "item_starforce_option": {
 *         "str": "string",
 *         "dex": "string",
 *         "int": "string",
 *         "luk": "string",
 *         "max_hp": "string",
 *         "max_mp": "string",
 *         "attack_power": "string",
 *         "magic_power": "string",
 *         "armor": "string",
 *         "speed": "string",
 *         "jump": "string"
 *       },
 *       "special_ring_level": 0,
 *       "date_expire": "2023-12-21T17:28+09:00"
 *     }
 *   ],
 *   "item_equipment_preset_1": [
 *     {
 *       "item_equipment_part": "string",
 *       "equipment_slot": "string",
 *       "item_name": "string",
 *       "item_icon": "string",
 *       "item_description": "string",
 *       "item_shape_name": "string",
 *       "item_shape_icon": "string",
 *       "item_gender": "string",
 *       "item_total_option": {
 *         "str": "string",
 *         "dex": "string",
 *         "int": "string",
 *         "luk": "string",
 *         "max_hp": "string",
 *         "max_mp": "string",
 *         "attack_power": "string",
 *         "magic_power": "string",
 *         "armor": "string",
 *         "speed": "string",
 *         "jump": "string",
 *         "boss_damage": "string",
 *         "ignore_monster_armor": "string",
 *         "all_stat": "string",
 *         "damage": "string",
 *         "equipment_level_decrease": 0,
 *         "max_hp_rate": "string",
 *         "max_mp_rate": "string"
 *       },
 *       "item_base_option": {
 *         "str": "string",
 *         "dex": "string",
 *         "int": "string",
 *         "luk": "string",
 *         "max_hp": "string",
 *         "max_mp": "string",
 *         "attack_power": "string",
 *         "magic_power": "string",
 *         "armor": "string",
 *         "speed": "string",
 *         "jump": "string",
 *         "boss_damage": "string",
 *         "ignore_monster_armor": "string",
 *         "all_stat": "string",
 *         "max_hp_rate": "string",
 *         "max_mp_rate": "string",
 *         "base_equipment_level": 0
 *       },
 *       "potential_option_grade": "string",
 *       "additional_potential_option_grade": "string",
 *       "potential_option_1": "string",
 *       "potential_option_2": "string",
 *       "potential_option_3": "string",
 *       "additional_potential_option_1": "string",
 *       "additional_potential_option_2": "string",
 *       "additional_potential_option_3": "string",
 *       "equipment_level_increase": 0,
 *       "item_exceptional_option": {
 *         "str": "string",
 *         "dex": "string",
 *         "int": "string",
 *         "luk": "string",
 *         "max_hp": "string",
 *         "max_mp": "string",
 *         "attack_power": "string",
 *         "magic_power": "string"
 *       },
 *       "item_add_option": {
 *         "str": "string",
 *         "dex": "string",
 *         "int": "string",
 *         "luk": "string",
 *         "max_hp": "string",
 *         "max_mp": "string",
 *         "attack_power": "string",
 *         "magic_power": "string",
 *         "armor": "string",
 *         "speed": "string",
 *         "jump": "string",
 *         "boss_damage": "string",
 *         "damage": "string",
 *         "all_stat": "string",
 *         "equipment_level_decrease": 0
 *       },
 *       "growth_exp": 0,
 *       "growth_level": 0,
 *       "scroll_upgrade": "string",
 *       "cuttable_count": "string",
 *       "golden_hammer_flag": "string",
 *       "scroll_resilience_count": "string",
 *       "scroll_upgradable_count": "string",
 *       "soul_name": "string",
 *       "soul_option": "string",
 *       "item_etc_option": {
 *         "str": "string",
 *         "dex": "string",
 *         "int": "string",
 *         "luk": "string",
 *         "max_hp": "string",
 *         "max_mp": "string",
 *         "attack_power": "string",
 *         "magic_power": "string",
 *         "armor": "string",
 *         "speed": "string",
 *         "jump": "string"
 *       },
 *       "starforce": "string",
 *       "starforce_scroll_flag": "string",
 *       "item_starforce_option": {
 *         "str": "string",
 *         "dex": "string",
 *         "int": "string",
 *         "luk": "string",
 *         "max_hp": "string",
 *         "max_mp": "string",
 *         "attack_power": "string",
 *         "magic_power": "string",
 *         "armor": "string",
 *         "speed": "string",
 *         "jump": "string"
 *       },
 *       "special_ring_level": 0,
 *       "date_expire": "2023-12-21T17:28+09:00"
 *     }
 *   ],
 *   "item_equipment_preset_2": [
 *     {
 *       "item_equipment_part": "string",
 *       "equipment_slot": "string",
 *       "item_name": "string",
 *       "item_icon": "string",
 *       "item_description": "string",
 *       "item_shape_name": "string",
 *       "item_shape_icon": "string",
 *       "item_gender": "string",
 *       "item_total_option": {
 *         "str": "string",
 *         "dex": "string",
 *         "int": "string",
 *         "luk": "string",
 *         "max_hp": "string",
 *         "max_mp": "string",
 *         "attack_power": "string",
 *         "magic_power": "string",
 *         "armor": "string",
 *         "speed": "string",
 *         "jump": "string",
 *         "boss_damage": "string",
 *         "ignore_monster_armor": "string",
 *         "all_stat": "string",
 *         "damage": "string",
 *         "equipment_level_decrease": 0,
 *         "max_hp_rate": "string",
 *         "max_mp_rate": "string"
 *       },
 *       "item_base_option": {
 *         "str": "string",
 *         "dex": "string",
 *         "int": "string",
 *         "luk": "string",
 *         "max_hp": "string",
 *         "max_mp": "string",
 *         "attack_power": "string",
 *         "magic_power": "string",
 *         "armor": "string",
 *         "speed": "string",
 *         "jump": "string",
 *         "boss_damage": "string",
 *         "ignore_monster_armor": "string",
 *         "all_stat": "string",
 *         "max_hp_rate": "string",
 *         "max_mp_rate": "string",
 *         "base_equipment_level": 0
 *       },
 *       "potential_option_grade": "string",
 *       "additional_potential_option_grade": "string",
 *       "potential_option_1": "string",
 *       "potential_option_2": "string",
 *       "potential_option_3": "string",
 *       "additional_potential_option_1": "string",
 *       "additional_potential_option_2": "string",
 *       "additional_potential_option_3": "string",
 *       "equipment_level_increase": 0,
 *       "item_exceptional_option": {
 *         "str": "string",
 *         "dex": "string",
 *         "int": "string",
 *         "luk": "string",
 *         "max_hp": "string",
 *         "max_mp": "string",
 *         "attack_power": "string",
 *         "magic_power": "string"
 *       },
 *       "item_add_option": {
 *         "str": "string",
 *         "dex": "string",
 *         "int": "string",
 *         "luk": "string",
 *         "max_hp": "string",
 *         "max_mp": "string",
 *         "attack_power": "string",
 *         "magic_power": "string",
 *         "armor": "string",
 *         "speed": "string",
 *         "jump": "string",
 *         "boss_damage": "string",
 *         "damage": "string",
 *         "all_stat": "string",
 *         "equipment_level_decrease": 0
 *       },
 *       "growth_exp": 0,
 *       "growth_level": 0,
 *       "scroll_upgrade": "string",
 *       "cuttable_count": "string",
 *       "golden_hammer_flag": "string",
 *       "scroll_resilience_count": "string",
 *       "scroll_upgradable_count": "string",
 *       "soul_name": "string",
 *       "soul_option": "string",
 *       "item_etc_option": {
 *         "str": "string",
 *         "dex": "string",
 *         "int": "string",
 *         "luk": "string",
 *         "max_hp": "string",
 *         "max_mp": "string",
 *         "attack_power": "string",
 *         "magic_power": "string",
 *         "armor": "string",
 *         "speed": "string",
 *         "jump": "string"
 *       },
 *       "starforce": "string",
 *       "starforce_scroll_flag": "string",
 *       "item_starforce_option": {
 *         "str": "string",
 *         "dex": "string",
 *         "int": "string",
 *         "luk": "string",
 *         "max_hp": "string",
 *         "max_mp": "string",
 *         "attack_power": "string",
 *         "magic_power": "string",
 *         "armor": "string",
 *         "speed": "string",
 *         "jump": "string"
 *       },
 *       "special_ring_level": 0,
 *       "date_expire": "2023-12-21T17:28+09:00"
 *     }
 *   ],
 *   "item_equipment_preset_3": [
 *     {
 *       "item_equipment_part": "string",
 *       "equipment_slot": "string",
 *       "item_name": "string",
 *       "item_icon": "string",
 *       "item_description": "string",
 *       "item_shape_name": "string",
 *       "item_shape_icon": "string",
 *       "item_gender": "string",
 *       "item_total_option": {
 *         "str": "string",
 *         "dex": "string",
 *         "int": "string",
 *         "luk": "string",
 *         "max_hp": "string",
 *         "max_mp": "string",
 *         "attack_power": "string",
 *         "magic_power": "string",
 *         "armor": "string",
 *         "speed": "string",
 *         "jump": "string",
 *         "boss_damage": "string",
 *         "ignore_monster_armor": "string",
 *         "all_stat": "string",
 *         "damage": "string",
 *         "equipment_level_decrease": 0,
 *         "max_hp_rate": "string",
 *         "max_mp_rate": "string"
 *       },
 *       "item_base_option": {
 *         "str": "string",
 *         "dex": "string",
 *         "int": "string",
 *         "luk": "string",
 *         "max_hp": "string",
 *         "max_mp": "string",
 *         "attack_power": "string",
 *         "magic_power": "string",
 *         "armor": "string",
 *         "speed": "string",
 *         "jump": "string",
 *         "boss_damage": "string",
 *         "ignore_monster_armor": "string",
 *         "all_stat": "string",
 *         "max_hp_rate": "string",
 *         "max_mp_rate": "string",
 *         "base_equipment_level": 0
 *       },
 *       "potential_option_grade": "string",
 *       "additional_potential_option_grade": "string",
 *       "potential_option_1": "string",
 *       "potential_option_2": "string",
 *       "potential_option_3": "string",
 *       "additional_potential_option_1": "string",
 *       "additional_potential_option_2": "string",
 *       "additional_potential_option_3": "string",
 *       "equipment_level_increase": 0,
 *       "item_exceptional_option": {
 *         "str": "string",
 *         "dex": "string",
 *         "int": "string",
 *         "luk": "string",
 *         "max_hp": "string",
 *         "max_mp": "string",
 *         "attack_power": "string",
 *         "magic_power": "string"
 *       },
 *       "item_add_option": {
 *         "str": "string",
 *         "dex": "string",
 *         "int": "string",
 *         "luk": "string",
 *         "max_hp": "string",
 *         "max_mp": "string",
 *         "attack_power": "string",
 *         "magic_power": "string",
 *         "armor": "string",
 *         "speed": "string",
 *         "jump": "string",
 *         "boss_damage": "string",
 *         "damage": "string",
 *         "all_stat": "string",
 *         "equipment_level_decrease": 0
 *       },
 *       "growth_exp": 0,
 *       "growth_level": 0,
 *       "scroll_upgrade": "string",
 *       "cuttable_count": "string",
 *       "golden_hammer_flag": "string",
 *       "scroll_resilience_count": "string",
 *       "scroll_upgradable_count": "string",
 *       "soul_name": "string",
 *       "soul_option": "string",
 *       "item_etc_option": {
 *         "str": "string",
 *         "dex": "string",
 *         "int": "string",
 *         "luk": "string",
 *         "max_hp": "string",
 *         "max_mp": "string",
 *         "attack_power": "string",
 *         "magic_power": "string",
 *         "armor": "string",
 *         "speed": "string",
 *         "jump": "string"
 *       },
 *       "starforce": "string",
 *       "starforce_scroll_flag": "string",
 *       "item_starforce_option": {
 *         "str": "string",
 *         "dex": "string",
 *         "int": "string",
 *         "luk": "string",
 *         "max_hp": "string",
 *         "max_mp": "string",
 *         "attack_power": "string",
 *         "magic_power": "string",
 *         "armor": "string",
 *         "speed": "string",
 *         "jump": "string"
 *       },
 *       "special_ring_level": 0,
 *       "date_expire": "2023-12-21T17:28+09:00"
 *     }
 *   ],
 *   "title": {
 *     "title_name": "string",
 *     "title_icon": "string",
 *     "title_description": "string",
 *     "date_expire": "2023-12-21T17:28+09:00",
 *     "date_option_expire": "2023-12-21T17:28+09:00"
 *   },
 *   "dragon_equipment": [
 *     {
 *       "item_equipment_part": "string",
 *       "equipment_slot": "string",
 *       "item_name": "string",
 *       "item_icon": "string",
 *       "item_description": "string",
 *       "item_shape_name": "string",
 *       "item_shape_icon": "string",
 *       "item_gender": "string",
 *       "item_total_option": {
 *         "str": "string",
 *         "dex": "string",
 *         "int": "string",
 *         "luk": "string",
 *         "max_hp": "string",
 *         "max_mp": "string",
 *         "attack_power": "string",
 *         "magic_power": "string",
 *         "armor": "string",
 *         "speed": "string",
 *         "jump": "string",
 *         "boss_damage": "string",
 *         "ignore_monster_armor": "string",
 *         "all_stat": "string",
 *         "damage": "string",
 *         "equipment_level_decrease": 0,
 *         "max_hp_rate": "string",
 *         "max_mp_rate": "string"
 *       },
 *       "item_base_option": {
 *         "str": "string",
 *         "dex": "string",
 *         "int": "string",
 *         "luk": "string",
 *         "max_hp": "string",
 *         "max_mp": "string",
 *         "attack_power": "string",
 *         "magic_power": "string",
 *         "armor": "string",
 *         "speed": "string",
 *         "jump": "string",
 *         "boss_damage": "string",
 *         "ignore_monster_armor": "string",
 *         "all_stat": "string",
 *         "max_hp_rate": "string",
 *         "max_mp_rate": "string",
 *         "base_equipment_level": 0
 *       },
 *       "equipment_level_increase": 0,
 *       "item_exceptional_option": {
 *         "str": "string",
 *         "dex": "string",
 *         "int": "string",
 *         "luk": "string",
 *         "max_hp": "string",
 *         "max_mp": "string",
 *         "attack_power": "string",
 *         "magic_power": "string"
 *       },
 *       "item_add_option": {
 *         "str": "string",
 *         "dex": "string",
 *         "int": "string",
 *         "luk": "string",
 *         "max_hp": "string",
 *         "max_mp": "string",
 *         "attack_power": "string",
 *         "magic_power": "string",
 *         "armor": "string",
 *         "speed": "string",
 *         "jump": "string",
 *         "boss_damage": "string",
 *         "damage": "string",
 *         "all_stat": "string",
 *         "equipment_level_decrease": 0
 *       },
 *       "growth_exp": 0,
 *       "growth_level": 0,
 *       "scroll_upgrade": "string",
 *       "cuttable_count": "string",
 *       "golden_hammer_flag": "string",
 *       "scroll_resilience_count": "string",
 *       "scroll_upgradable_count": "string",
 *       "soul_name": "string",
 *       "soul_option": "string",
 *       "item_etc_option": {
 *         "str": "string",
 *         "dex": "string",
 *         "int": "string",
 *         "luk": "string",
 *         "max_hp": "string",
 *         "max_mp": "string",
 *         "attack_power": "string",
 *         "magic_power": "string",
 *         "armor": "string",
 *         "speed": "string",
 *         "jump": "string"
 *       },
 *       "starforce": "string",
 *       "starforce_scroll_flag": "string",
 *       "item_starforce_option": {
 *         "str": "string",
 *         "dex": "string",
 *         "int": "string",
 *         "luk": "string",
 *         "max_hp": "string",
 *         "max_mp": "string",
 *         "attack_power": "string",
 *         "magic_power": "string",
 *         "armor": "string",
 *         "speed": "string",
 *         "jump": "string"
 *       },
 *       "special_ring_level": 0,
 *       "date_expire": "2023-12-21T17:28+09:00"
 *     }
 *   ],
 *   "mechanic_equipment": [
 *     {
 *       "item_equipment_part": "string",
 *       "equipment_slot": "string",
 *       "item_name": "string",
 *       "item_icon": "string",
 *       "item_description": "string",
 *       "item_shape_name": "string",
 *       "item_shape_icon": "string",
 *       "item_gender": "string",
 *       "item_total_option": {
 *         "str": "string",
 *         "dex": "string",
 *         "int": "string",
 *         "luk": "string",
 *         "max_hp": "string",
 *         "max_mp": "string",
 *         "attack_power": "string",
 *         "magic_power": "string",
 *         "armor": "string",
 *         "speed": "string",
 *         "jump": "string",
 *         "boss_damage": "string",
 *         "ignore_monster_armor": "string",
 *         "all_stat": "string",
 *         "damage": "string",
 *         "equipment_level_decrease": 0,
 *         "max_hp_rate": "string",
 *         "max_mp_rate": "string"
 *       },
 *       "item_base_option": {
 *         "str": "string",
 *         "dex": "string",
 *         "int": "string",
 *         "luk": "string",
 *         "max_hp": "string",
 *         "max_mp": "string",
 *         "attack_power": "string",
 *         "magic_power": "string",
 *         "armor": "string",
 *         "speed": "string",
 *         "jump": "string",
 *         "boss_damage": "string",
 *         "ignore_monster_armor": "string",
 *         "all_stat": "string",
 *         "max_hp_rate": "string",
 *         "max_mp_rate": "string",
 *         "base_equipment_level": 0
 *       },
 *       "equipment_level_increase": 0,
 *       "item_exceptional_option": {
 *         "str": "string",
 *         "dex": "string",
 *         "int": "string",
 *         "luk": "string",
 *         "max_hp": "string",
 *         "max_mp": "string",
 *         "attack_power": "string",
 *         "magic_power": "string"
 *       },
 *       "item_add_option": {
 *         "str": "string",
 *         "dex": "string",
 *         "int": "string",
 *         "luk": "string",
 *         "max_hp": "string",
 *         "max_mp": "string",
 *         "attack_power": "string",
 *         "magic_power": "string",
 *         "armor": "string",
 *         "speed": "string",
 *         "jump": "string",
 *         "boss_damage": "string",
 *         "damage": "string",
 *         "all_stat": "string",
 *         "equipment_level_decrease": 0
 *       },
 *       "growth_exp": 0,
 *       "growth_level": 0,
 *       "scroll_upgrade": "string",
 *       "cuttable_count": "string",
 *       "golden_hammer_flag": "string",
 *       "scroll_resilience_count": "string",
 *       "scroll_upgradable_count": "string",
 *       "soul_name": "string",
 *       "soul_option": "string",
 *       "item_etc_option": {
 *         "str": "string",
 *         "dex": "string",
 *         "int": "string",
 *         "luk": "string",
 *         "max_hp": "string",
 *         "max_mp": "string",
 *         "attack_power": "string",
 *         "magic_power": "string",
 *         "armor": "string",
 *         "speed": "string",
 *         "jump": "string"
 *       },
 *       "starforce": "string",
 *       "starforce_scroll_flag": "string",
 *       "item_starforce_option": {
 *         "str": "string",
 *         "dex": "string",
 *         "int": "string",
 *         "luk": "string",
 *         "max_hp": "string",
 *         "max_mp": "string",
 *         "attack_power": "string",
 *         "magic_power": "string",
 *         "armor": "string",
 *         "speed": "string",
 *         "jump": "string"
 *       },
 *       "special_ring_level": 0,
 *       "date_expire": "2023-12-21T17:28+09:00"
 *     }
 *   ]
 * }
 */

@Getter @Setter
public class CharacterItemEquipment {

    private LocalDateTime date;
    private String character_gender;
    private String character_class;
    private int preset_no;
    private List<ItemEquipment> item_equipment;
    private List<ItemEquipment> item_equipment_preset_1;
    private List<ItemEquipment> item_equipment_preset_2;
    private List<ItemEquipment> item_equipment_preset_3;

    private Title title;
    private List<DragonEquipment> dragon_equipment;
    private List<MechanicEquipment> mechanic_equipment;

    public void setDate(Timestamp dateTime) {
        date = dateTime.toLocalDateTime();
    }

    public String getDate() {
        return date.toString();
    }
}
